# GitHub Sponsors configuration
# https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

# github: [civicbase]
# patreon: civicbase
# open_collective: civicbase
# ko_fi: civicbase
# custom: ['https://civicbase.org/donate']

